
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlwcxtvfncrmyqisbyrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsd2N4dHZmbmNybXlxaXNieXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDI1OTQsImV4cCI6MjA2MDk3ODU5NH0.hXab3MGoX7WXK40qmzf7tl_fB5xWF0YMP10z5Fq0Llc";

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
